package Selenium;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class RegisterTest1 {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @Test
    public void register() {
        driver.get("https://demowebshop.tricentis.com/register");
        driver.findElement(By.id("gender-male")).click();
        driver.findElement(By.id("FirstName")).sendKeys("First");
        driver.findElement(By.id("LastName")).sendKeys("Last");
        vars.put("LastName", driver.findElement(By.id("LastName")).getAttribute("value"));
        vars.put("FirstName", driver.findElement(By.id("FirstName")).getAttribute("value"));
        driver.findElement(By.id("Email")).sendKeys(vars.get("FirstName").toString() + vars.get("LastName").toString() + "@gmail.com");
        driver.findElement(By.id("Password")).sendKeys("123456");
        vars.put("PassWord", driver.findElement(By.id("Password")).getAttribute("value"));
        driver.findElement(By.id("ConfirmPassword")).sendKeys(vars.get("PassWord").toString());
        driver.findElement(By.id("register-button")).click();
    }
}

